name: Fork Sync

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.4
        with:
          owner: Ren0503
          token: ${{ secrets.PERSONAL_TOKEN }}
          base: master
          head: master
          auto_approve: true
